import {
  IconActivity,
  IconAssembly,
  IconAsset,
  IconAsterisk,
  IconAsteriskSimple,
  IconAugmentedReality2,
  IconBackhoe,
  IconBadgeTm,
  IconBoxModel,
  IconBoxMultiple,
  IconBug,
  IconCategory,
  IconCloudComputing,
  IconDatabase,
  IconDevices,
  IconGitBranch,
  IconHeartHandshake,
  IconMap2,
  IconMapPin,
  IconNetwork,
  IconServer,
  IconServerBolt,
  IconStatusChange,
  IconTicket,
  IconUsers,
  IconWindow,
  IconUserCheck,
  IconLockAccess, 
} from '@tabler/icons';
import WindowIcon from '@mui/icons-material/Window';
import HomeIcon from '@mui/icons-material/Home';



const Menuitems = [
  {
    navlabel: true,
    subheader: 'Dashboard',
  },
  {
    id: 4,
    title: 'Home',
    icon: HomeIcon,
    href: '/dashboard/Home',
    // chip: 'New',
    chipColor: 'secondary',
    disabled: false,
  },
  {
    id: 2,
    title: 'Dashboard',
    icon: WindowIcon,
    href: '/dashboard/DashboardSummary',
    // chip: 'New',
    chipColor: 'secondary',
    disabled: false,
  },
  {
    id: 3,
    title: 'Network Status',
    icon: IconNetwork,
    href: '/dashboard/networkStatus',
    // chip: 'New',
    chipColor: 'secondary',
    disabled: false,
  },
  {
    id: 26,
    title: 'Server Center',
    icon: IconDatabase,
    href: '/dashboard/dataCenter',
    // chip: 'New',
    chipColor: 'secondary',
    disabled: false,
  },
  {
    id: 2,
    title: 'Device Info',
    icon: IconDevices,
    href: '/dashboard/deviceInfo',
    // chip: 'New',
    chipColor: 'secondary',
    disabled: false,
  },
  {
    id: 1,
    title: 'Help Desk',
    icon: IconHeartHandshake,
    href: '/dashboard/helpDesk',
    // chip: 'New',
    chipColor: 'secondary',
  },
  {
    id: 4,
    title: 'Location Info',
    icon: IconMap2,
    href: '/dashboard/locationInfo',
    // chip: 'New',
    chipColor: 'secondary',
    disabled: false,
  },
  {
    navlabel: true,
    subheader: 'Admin Panel',
  },
  {
    id: 5,
    title: 'HelpDesk Config',
    icon: IconBoxMultiple,
    // href: '/admin/help-desk/activity',
    children: [
      {
        id: 20,
        title: 'Tickets',
        icon: IconTicket,
        href: '/help-desk/tickets',
        // chipColor: 'secondary',
        // disabled: true,
      },
      {
        id: 21,
        title: 'Activity',
        icon: IconActivity,
        href: '/help-desk/activity',
      },
      {
        id: 22,
        title: 'Category',
        icon: IconCategory,
        href: '/help-desk/category',
      },
      {
        id: 23,
        title: 'Incident',
        icon: IconBug,
        href: '/help-desk/incident',
      },
      {
        id: 24,
        title: 'Severity',
        icon: IconAsterisk,
        href: '/help-desk/severity',
      },
      {
        id: 25,
        title: 'Status',
        icon: IconStatusChange,
        href: '/help-desk/status',
      },
      {
        id: 28,
        title: 'Location',
        icon: IconMapPin,
        href: '/help-desk/location',
      },
      {
        id: 29,
        title: 'Department',
        icon: IconWindow,
        href: '/help-desk/department',
      },
    ],
  },
  {
    id: 6,
    title: 'Asset Config',
    icon: IconAssembly,
    // href: '/admin/asset/activity',
    children: [
      {
        id: 7,
        title: 'Company',
        icon: IconGitBranch,
        href: '/asset/company',
      },
      {
        id: 8,
        title: 'Equipment',
        icon: IconBackhoe,
        href: '/asset/equipment',
      },
      {
        id: 9,
        title: 'User',
        icon: IconUsers,
        href: '/asset/user',
      },
      {
        id: 10,
        title: 'Asset Info',
        icon: IconAsset,
        href: '/asset/asset-info',
      },
      {
        id: 11,
        title: 'Brand',
        icon: IconBadgeTm,
        href: '/asset/brand',
      },
      {
        id: 12,
        title: 'Category',
        icon: IconCategory,
        href: '/asset/category',
      },
      {
        id: 13,
        title: 'Equipment Type',
        icon: IconAugmentedReality2,
        href: '/asset/equipment-type',
      },
      {
        id: 14,
        title: 'Location',
        icon: IconMapPin,
        href: '/asset/location',
      },
      {
        id: 15,
        title: 'Model',
        icon: IconBoxModel,
        href: '/asset/model',
      },
      {
        id: 16,
        title: 'Severity',
        icon: IconAsteriskSimple,
        href: '/asset/severity',
      },
      {
        id: 17,
        title: 'Device Adding',
        icon: IconServer,
        href: '/asset/server',
      },
      {
        id: 18,
        title: 'Device Types',
        icon: IconServerBolt,
        href: '/asset/server-templates',
      },
      {
        id: 19,
        title: 'Device Category Group',
        icon: IconCloudComputing,
        href: '/asset/server-templates-group',
      },
    ],
  },

  {
    id: 30,
    title: 'User Access',
    icon: IconLockAccess,
    href: '/user-access',
    // chip: 'New',
    chipColor: 'secondary',
    disabled: false,
  },
];
export default Menuitems;